Fix debug build
eagleivg/xray-16 pull request #1
Opened 2018-11-02 19:35 UTC by drug007

2018-11-02 20:43 UTC, eagleivg requested changes

2018-11-02 20:43 UTC, eagleivg commented on src/xrCDB/ISpatial.cpp
> +#ifndef LINUX // disabled for Linux because linking issue due to IGameObject belongs to xrEngine
Better hide under define "else" part an in LINUX macro branch do some this: xrDebug::Fatal(DEBUG_INFO, "Invalid PS or other spatial position (%s)", O->cName().c_str());

2018-11-02 21:24 UTC, drug007 commented on src/xrCDB/ISpatial.cpp
> +#ifndef LINUX // disabled for Linux because linking issue due to IGameObject belongs to xrEngine
Only `xrDebug::Fatal(DEBUG_INFO, "Invalid PS or other spatial position");` possible because `O` is null in this case.

2018-11-03 05:08 UTC, eagleivg approved these changes

2018-11-03 05:08 UTC, merged